//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portales.Dal.Model
{
    using System;
    
    [Flags]
    public enum FileType : int
    {
        Avatar = 0,
        Resume = 1
    }
}
